" Set tabs size and convert to spaces
set tabstop=2
set shiftwidth=2
set expandtab


" Set syntax highlighting on
syntax on


" Turn on autoindent and smart index
set autoindent
set smartindent


" Display line numbers
set number


" Enable mouse
set mouse=a


" Set encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8


" Set the backspace
set backspace=indent,eol,start


" Seaching
" highlight all search, add incremental search,
" ignore case, and use smart case
set hlsearch
set incsearch
set ignorecase
set smartcase


" Display the ruler
set ruler


" Show the command at the bottom
set showcmd



